#!/usr/bin/env sh

MDIR=aws-clerk-dev-martin
HOST=aws-clerk-dev-martin
HDIR=/home/ec2-user

case $1 in
    "dev")
        MDIR=aws-clerk-dev-martin
        HOST=aws-clerk-dev-martin
        HDIR=/home/ec2-user
        ;;
    "proc")
        MDIR=aws-clerk-proc
        HOST=aws-clerk-proc
        HDIR=/home/ec2-user
        ;;
    "gulag")
        MDIR=gulag
        HOST=gulag.martinnj.dk
        HDIR=/home/martin
        ;;
    "clusterfs")
        MDIR=clusterfs
        HOST=pi@10.42.43.21
        HDIR=/clusterfs
        ;;
    *)
        MDIR=$1
        HOST=$1
        HDIR=/
        ;;
esac

# Create mountpoint
mkdir -p "~/$MDIR"

# Mount remote home folder
sshfs $HOST:$HDIR "$MDIR"
